### ISSUE TITLE
3. 第一个组件 Button

### ISSUE THREAD

**Issue by xzfd1010** [xzfd1010/nick-vue-wheels#4]
# 用例分析
1. 按钮存在不同的状态
    * hover
    * active
    * focus状态
    * disabled
2. 按钮可以自定义文字
3. 按钮可以添加图标
4. 图标和文字的位置 
5. loading状态
6. 按钮可以点击，触发点击事件
7. 多个按钮可以合并成一个按钮组

# 实现需求
1. 创建组件
首先创建 `Button.vue`文件，其中只包含一个button元素，为了能够添加文字，在button内部添加slot标签。
```vue
<template>
  <button class="l-button">
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'LButton',
}
</script>
```
2. 给button添加各种状态的样式
为了方便，将某些样式作为scss变量提取出来；这里唯一需要注意的就是focus状态，需要去掉浏览器默认的蓝色边框。
```scss
  $border-color-hover: #666;
  $border-color: #999;
  $border-radius: 4px;
  $button-active-bg: #eee;
  $button-bg: white;
  $button-height: 32px;
  $color: #333;
  $disabled-color: #bbb;
  $font-size: 14px;
  .l-button {
    font-size: $font-size;
    height: $button-height;
    background: $button-bg;
    border-radius: $border-radius;
    border: 1px solid $border-color;
    padding: 0 1em;
    color: $color;
    &:hover {
      border-color: $border-color-hover;
    }
    &:active {
      background-color: $button-active-bg;
    }
    &:focus {
      outline: none;  // 处理按钮点过后的蓝色边框
    }
    &:disabled {
      color: $disabled-color; // graytext是浏览器的默认样式，#d3d3d3
      cursor: not-allowed;
      background-image: none;
      background-color: #fff;
      border-color: #ebeef5;
    }
  }
```
在props中定义disabled变量，用来处理disabled状态，这个比较简单，就不多赘述了。
3. 按钮添加图标
这里我们使用[阿里巴巴的字体图标库](https://www.iconfont.cn/)，采用svg方案，我主要选用了下面这些图标，可以按照自己的喜好随意选图标，这里给出我选用的图标的[文件地址](//at.alicdn.com/t/font_1443855_gerja8e2v3.js)，svg图标的使用方法参考[文档]。(https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8cf4382a&helptype=code)
![image](https://user-images.githubusercontent.com/15313636/70698052-a6460180-1d01-11ea-89c5-018cb7c556ca.png)
为了方便使用图标，我们再创建一个 `icon.vue` 文件，只接受一个name作为props，作为icon的图标名，文件内容如下：
```vue
<template>
  <svg class="l-icon">
    <use :xlink:href="`#icon-${name}`"></use>
  </svg>
</template>

<script>
import './svg'

export default {
  name: 'icon',
  props: ['name']
}
</script>

<style lang="scss" scoped>
  .l-icon {
    width: 1em;
    height: 1em;
  }
</style>

```
之后在Button中引用Icon作为component即可，同理Button也应该接收一个属性代表icon的name，同时传给icon。
```vue
<icon class="icon" v-if="icon" :name="icon"></icon>
```
此时为了icon和文字能够对齐，给button添加居中的样式，直接使用flex布局即可，考虑到button本身是inline元素，所以使用inline-flex，相关代码：
```scss
.l-button{
    display: inline-flex;
    align-items: center;
    justify-content: center;
    > .icon{
        margin-right: .1em;
    }
}
```
4. 图标和文字的位置
现在图标在左边，文字在右边，有时候我们会想要文字在右边，图标在左边。因为slot中的内容传什么都行，不一定只是文字，所以最好把slot用一个标签包起来，来与icon做定位。同时Button组件应该接收一个代表图标位置的props，这里命名为”iconPosition"，根据这个属性给button添加类名“icon-left”或者“icon-right”
那到底如何实现文字居左、图标居右的效果呢？还是要用到flex的特性——order，关键代码
```scss
.l-button{
   > .icon {
      order: 1;
      margin-right: .1em;
    }
    > .content {
      order: 2;
    }
    &.icon-right {
      > .icon {
        order: 2;
        margin-left: .1em;
        margin-right: 0;
      }
      > .content {
        order: 1;
      }
    }
}
```
关于iconPosition，我们这里只能接受left和right的值，所以要进行校验：
```js
iconPosition: {
        type: String,
        default: 'left',
        validator (value) {
          return value === 'left' || value === 'right'
        }
}
```
5. loading状态
依旧是用props实现，接收一个loading属性代表是否需要进入loading状态，此时应该显示一个loading的图标，并且不断旋转。
另外当显示loading的图标时，其他的图标应该隐藏。
```vue
<icon class="icon" v-if="icon && !loading" :name="icon"></icon>
<icon class="icon loading" v-if="loading" name="loading"></icon>
```
6. 按钮触发点击事件
直接给按钮绑定点击事件 `@click="$emit('click')"` 即可，此时点击button触发的点击事件就会触发绑定在组件上的点击事件。

7. 按钮组的实现
类似element的[按钮组](https://element.eleme.io/#/zh-CN/component/button#an-niu-zu)。
创建ButtonGroup.vue文件，html结构就是 div包一个slot标签，因为button-group的子元素只能是button，所以应该对它的children进行检验：
```js
   mounted () {
      for (let node of this.$el.children) {
        if (node.nodeName.toLowerCase() !== 'button') {
          console.warn(`button-group的内部应该都是button，但你写的是${node.nodeName.toLowerCase()}`)
        }
      }
    }
```
按钮组的主要需求就是两个按钮中间的border，只留下一条，考虑两种方案：
    * 让右边的按钮border-left为0；
    * 让右边的按钮 margin-left:-1px;
第一种方案在悬浮的时候，会只剩下三条边，所以采用第二种方案。hover时还要让当前hover的按钮层级高一点。
另外只有第一个按钮和最后一个按钮保留border-radius。所以就把相关的scss变量提取出来，代码如下：
```scss
  @import "../../styles/var";
  .g-button-group {
    display: inline-flex;
    vertical-align: middle;
    > .g-button {
      border-radius: 0;
      &:not(:first-child) {
        margin-left: -1px;
      }
      &:first-child {
        border-top-left-radius: $border-radius;
        border-bottom-left-radius: $border-radius;
      }
      &:last-child {
        border-top-right-radius: $border-radius;
        border-bottom-right-radius: $border-radius;
      }
      &:hover {
        position: relative;
        z-index: 1;
      }
    }
  }
```

# 单元测试

# 相关文件
