### ISSUE TITLE
Pager组件

### ISSUE THREAD

**Issue by xzfd1010** [xzfd1010/nick-vue-wheels#6]
# 需求分析
要写一个Pager组件，来进行分页，我们至少应该接受两个参数，一个是总的页数`totalPage`，一个是当前页`currentPage`，需求我们也主要围绕这两个部分展开。
1. 显示页数
2. 页数较长时，应该省略部分页码，用`...`替代，而显示的页数应该根据currentPage来计算
3. 支持翻页操作，应该有前进和后退按钮
4. 点击页码的时候，应该跳转到对应页数
5. 参考ant-design的参数发现一个需求是，当只有1页时，可以选择是否隐藏Pager
# 功能实现
## 搭建基本结构
我们设想的最基本的使用方式应该是这样的：
```vue
<pager :total-page="20" :current-page="1"></pager>
```
那么在组件内部就应该渲染出页数，最基本的页面结构如下：
```vue
  <div class="my-pager">
    <span v-for="page in pages" class="my-pager-item">
      {{page}}
    </span>
  </div>
```
其中pages代表当前应该渲染的页码的数组，
```javascript
data(){
  let pages = []
  for(let i = 1;i < this.totalPage; i++){
     pages.push(i)
  }
  return {pages}
}

```
## 实现样式
首先需要确定一点，分页器的页码应该是圆形的还是方形的，当只存在个位数的页码时，这个无关紧要；但当页数 > 10时，圆形的页码会变形为椭圆，所以样式上选择方形的。
```scss
.my-pager {
    &-item {
      border: 1px solid $grey;
      border-radius: $border-radius;
      padding: 0 4px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
      min-width: 20px;
      height: 20px;
      margin: 0 4px;
      cursor: pointer;
  }
}
```
## 确定应该显示的页码
参考Ant design，首页和最后一页是一定要显示的
# 参考
[Ant design的pagination组件](https://ant.design/components/pagination-cn/)
